[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PySynthMRI"
authors = [{name = "Luca Peretti", email = "luca.peretti@fsm.unipi.it"}]
dynamic = ["version", "description"]
